In [40]:
import urllib.request, json
import os
import numpy as np

sudoku_data = 'sudoku_puzzle.json'
table = np.zeros((9,9))

def get_puzzle():

    if os.stat(sudoku_data).st_size == 0:
        url = "http://www.cs.utep.edu/cheon/ws/sudoku/new/?level=3&size=9"

        req = urllib.request.Request(url)

        r = urllib.request.urlopen(req).read()
        cont = json.loads(r.decode('utf-8'))


        f = open(sudoku_data, "w+")
        json.dump(cont, f)
        f.close()
    else:
        with open(sudoku_data) as json_file:
            cont = json.load(json_file)
    return cont

def create_game(sudoku_data: list):
    global table
    new_table = sudoku_data['squares']
    for column in new_table:
        x = column['x']
        y = column['y']
        value = column['value']
        table[x,y] = int(value)
        
    return table


In [58]:
def possible(table, x, y, value):
    '''
    x = num.get('x')
    y = num.get('y')
    value = num.get('value')
    '''
    for x_ax in range(9):
        if table[x_ax][y]==value:
            return False
    
    for y_ax in range(9):
        if table[x][y_ax]==value:
            return False
    
    return True 
        
puzzle_json = get_puzzle()
current_game = create_game(puzzle_json)
possible(current_game, x=0,y=0,value=5)


True

In [48]:
#from load_json import get_puzzle


if __name__ == "__main__":
    puzzle_json = get_puzzle()
    current_game = create_game(puzzle_json)
    
    print(current_game)
    



[[1. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 2. 0. 4. 0. 0. 0. 9.]
 [0. 9. 0. 0. 0. 3. 1. 0. 0.]
 [2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 5. 4. 0. 0. 6. 8. 0.]
 [9. 7. 0. 0. 6. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 7.]]
