In [55]:
import urllib.request, json
import os
import numpy as np

sudoku_data = 'sudoku_puzzle.json'
table = np.zeros((9,9))

def load_puzzle():

    if os.stat(sudoku_data).st_size == 0:
        url = "http://www.cs.utep.edu/cheon/ws/sudoku/new/?level=3&size=9"

        req = urllib.request.Request(url)

        r = urllib.request.urlopen(req).read()
        cont = json.loads(r.decode('utf-8'))


        f = open(sudoku_data, "w+")
        json.dump(cont, f)
        f.close()
    else:
        with open(sudoku_data) as json_file:
            cont = json.load(json_file)
            
    return create_game(cont)

def create_game(sudoku_data: list):
    global table
    new_table = sudoku_data['squares']
    for column in new_table:
        x = column['x']
        y = column['y']
        value = column['value']
        table[x,y] = int(value)
        
    return table


In [ ]:
def possible(table, x, y, value):
    '''
    x = num.get('x')
    y = num.get('y')
    value = num.get('value')
    '''
    if table[x][y]!=0: return False 
    for x_ax in range(9):
        if table[x_ax][y]==value:
            return False
    
    for y_ax in range(9):
        if table[x][y_ax]==value:
            return False
        

In [72]:
def possible(table, x_val, y_val, value):
    '''
    x = num.get('x')
    y = num.get('y')
    value = num.get('value')
    '''
    x = y_val
    y = x_val
    
    if table[x][y]!=0: return False 
    for i in range(9):
        if table[x][i]==value or table[i][y]==value:
            return False
    
    x = x-x%3
    y = y-y%3
    for x_box in range(x,x+3):
        for y_box in range(y,y+3):
            if table[y_box][x_box]==value:
                return False
    
    return True 
        
current_game = load_puzzle()
possible(current_game, x_val=1,y_val=4,value=4)


True

In [67]:
table = load_puzzle()
x = 8
y = 7

value = 8

x = x-x%3
y = y-y%3
print('x:',x)
print('y:',y)


for x_box in range(x,x+3):
    for y_box in range(y,y+3):
        print('table',x_box,y_box, '=',table[x_box][y_box])
        if table[x_box][y_box]==value:
            print('FALSE')
print(table)


x: 6
y: 6
table 6 6 = 6.0
table 6 7 = 8.0
FALSE
table 6 8 = 0.0
table 7 6 = 0.0
table 7 7 = 0.0
table 7 8 = 0.0
table 8 6 = 0.0
table 8 7 = 0.0
table 8 8 = 7.0
[[1. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 2. 0. 4. 0. 0. 0. 9.]
 [0. 9. 0. 0. 0. 3. 1. 0. 0.]
 [2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 5. 4. 0. 0. 6. 8. 0.]
 [9. 7. 0. 0. 6. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 7.]]


In [56]:
#from load_json import get_puzzle


if __name__ == "__main__":
    '''
    puzzle_json = load_puzzle()
    current_game = create_game(puzzle_json)
    '''
    new_game = load_puzzle()
    print(new_game)
    



[[1. 0. 0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 2. 0. 4. 0. 0. 0. 9.]
 [0. 9. 0. 0. 0. 3. 1. 0. 0.]
 [2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 5. 4. 0. 0. 6. 8. 0.]
 [9. 7. 0. 0. 6. 8. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 7.]]
